name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-status:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    outputs:
      is_draft: ${{ steps.check.outputs.is_draft }}
    steps:
      - id: check
        run: echo "is_draft=${{ github.event.pull_request.draft }}" >> "$GITHUB_OUTPUT"

  Test:
    needs: pr-status
    if: needs.pr-status.outputs.is_draft == 'false'
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.submodule_pull_pat }}

    - name: Run tests
      run: |
        set -eo pipefail
        echo "run test.."
