name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    # This condition ensures tests are skipped for draft PRs but run in all other scenarios you've described.
    if: >
      github.event_name != 'pull_request' ||
      github.event.pull_request.draft == false
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running tests..."
