name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main
jobs:
  Test:
    needs: pr-status
    if: >
      github.event_name != 'pull_request' ||
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Run tests
      run: |
        set -eo pipefail
        echo "run test.."
