name: Check CI Status
on:
  workflow_run:
    workflows: ["Test", "Fake CI Check"]
    types:
      - completed

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest commit SHA on main branch
        id: get-sha
        run: |
          SHA=$(curl --location --request GET 'https://api.github.com/repos/seaguest/githubaction/commits/main' \
          --header 'Authorization: Bearer ${{ secrets.GH_TOKEN }}' \
          --header 'Accept: application/vnd.github.v3+json' | jq -r '.sha')
          echo "SHA of latest commit on main branch: $SHA"
          echo "::set-output name=sha::$SHA"

      - name: Get check-runs for the latest commit
        run: |
          CHECK_RUNS=$(curl --location --request GET "https://api.github.com/repos/seaguest/githubaction/commits/${{ steps.get-sha.outputs.sha }}/check-runs" \
          --header 'Authorization: Bearer ${{ secrets.GH_TOKEN }}' \
          --header 'Accept: application/vnd.github.v3+json' | jq '.check_runs[] | {name: .name, conclusion: .conclusion}')
          echo "Check runs for latest commit:"
          echo "$CHECK_RUNS"
