name: Fake CI Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fake_check:
    runs-on: ubuntu-latest
    steps:
    - name: Always fail
      run: exit 1
